name: Deploy to Ipfs via the Crust

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Install & Build
        run: npm install && npm run docs:build

      - name: Upload to ipfs
        id: upload
        uses: crustio/ipfs-upload-action@v1.0.2
        with:
          path: './docs/.vuepress/dist'
          crust-secret-key: ${{ secrets.CRUST_SECRET_KEY }}
          
      - run: echo ${{ steps.upload.outputs.hash }}
